services:
  - type: web
    name: vitalityhub
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_1:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
